package com.ftn.sbnz.kjar.backward

import com.ftn.sbnz.model.models.GoalDependency;
import com.ftn.sbnz.model.models.GoalStatus;
import com.ftn.sbnz.model.models.SeedQuality;
import com.ftn.sbnz.model.models.SoilCondition;
import com.ftn.sbnz.model.models.WarningEvent;
import com.ftn.sbnz.model.models.ParameterEvaluation;

import com.ftn.sbnz.model.enums.SeedStatus;
import com.ftn.sbnz.model.enums.SoilStatus;
import com.ftn.sbnz.model.enums.ParameterStatus;



query failedRequirement(String goal, String failedGoal, String reason)
    (
        GoalDependency(goal, failedGoal;)
        and
        GoalStatus(failedGoal, false, reason;)
    )
    or
    (
        GoalDependency(goal, middle;)
        and
        failedRequirement(middle, failedGoal, reason;)
    )
end


rule "Goal failed from ParameterEvaluation"
    salience 40
    when
        $pe : ParameterEvaluation(status == ParameterStatus.FAILED, $name : parameterName, $reason : reason)
    then
        insert(new GoalStatus($name, false, $reason));
end

rule "Goal needs processing from ParameterEvaluation"
    salience 40
    when
        $pe : ParameterEvaluation(status == ParameterStatus.NEEDS_PROCESSING, $name : parameterName, $reason : reason)
    then
        insert(new GoalStatus($name, false, $reason));
end

rule "CEP detected problem"
    salience 40
    when
        $w : WarningEvent(
            type == "STORAGE_OVERHEAT" ||
            type == "STORAGE_HUMIDITY" ||
            type == "STORAGE_PEST" ||
            type == "SOIL_OVERMOISTURE" ||
            type == "SOIL_DRY" ||
            type == "SOIL_COLD"
        )
    then
        insert(new GoalStatus($w.getType(), false, $w.getMessage()));
end